widgetTheme=widget-themes/oval
primaryColor=#ffcc32
secondaryColor=#ffcc32
labelColor=#ffffff
hideWhenOffline=false
contactMail=admin@hallate.gov.py
loadingLabel=Cargando...
loginError=Error de inicio de sesión
chatHeader=Hablemos
startInfo=Por favor complete el siguiente formulario para iniciar el chat
widgetWidth=337
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Empezar
backLabel=Atrás
initMessageBody=¿Hola, como puedo ayudarte?
initMessageAuthor=Operador
chatInputLabel=Escribe tu pregunta
timeDaysAgo=día(s) atrás
timeHoursAgo=hour(s) ago
timeMinutesAgo=minuto(s) atrás
timeSecondsAgo=segundo(s) atrás
offlineMessage=Operador fuera de línea
toggleSoundLabel=Efectos de sonido
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticones
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Alternar a pantalla completa
endChatLabel=Termine el chat
endChatConfirmQuestion=¿Estás seguro?
endChatConfirm=Sí
endChatCancel=Cancelar
contactHeader=Hablemos
contactInfo=Todos los operadores están fuera de línea. Utilice el siguiente formulario para enviarnos un correo electrónico con su pregunta.
contactNameLabel=Su nombre
contactMailLabel=Su e-mail
contactQuestionLabel=Su consulta
contactSendLabel=Enviar
contactSuccessHeader=Mensaje enviado
contactSuccessMessage=Tu pregunta ha sido enviada. ¡Gracias!
contactErrorHeader=Error
contactErrorMessage=Hubo un error al enviar su pregunta
headerHeight=45
installed=1
autoShowWidgetAfter=200
autoShowWidget=false
askForMail=true
notificationIcon=img/notification.png
